# SySeBa 2 native default configuration
[SETTINGS]
source = C:\ProgramData\SySeBa\source
backup = C:\ProgramData\SySeBa\backup
restore = C:\ProgramData\SySeBa\restore
log = C:\ProgramData\SySeBa\syseba.log
threads = 4
