# SySeBa 2 native default configuration
[SETTINGS]
source = /Users/Shared/SySeBa/source
backup = /Users/Shared/SySeBa/backup
restore = /Users/Shared/SySeBa/restore
log = /usr/local/var/log/syseba/syseba.log
threads = 4
