set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_SYSTEM_VERSION 20.0)

if(DEFINED ENV{ZIG} AND NOT "$ENV{ZIG}" STREQUAL "")
  set(CMAKE_C_COMPILER "$ENV{ZIG}")
else()
  find_program(SYSEBA_ZIG_EXECUTABLE NAMES zig REQUIRED)
  set(CMAKE_C_COMPILER "${SYSEBA_ZIG_EXECUTABLE}")
endif()
set(CMAKE_C_COMPILER_ARG1 cc)
set(CMAKE_C_FLAGS_INIT
    "-target aarch64-macos-none -mmacosx-version-min=11.0")
set(CMAKE_EXE_LINKER_FLAGS_INIT
    "-target aarch64-macos-none -mmacosx-version-min=11.0")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
