if(NOT DEFINED OUTPUT_C OR NOT DEFINED OUTPUT_H)
  message(FATAL_ERROR "OUTPUT_C and OUTPUT_H are required")
endif()

function(syseba_append_asset input symbol)
  if(NOT EXISTS "${input}")
    message(FATAL_ERROR "Embedded asset not found: ${input}")
  endif()

  file(READ "${input}" content HEX)
  string(LENGTH "${content}" hex_length)
  math(EXPR byte_length "${hex_length} / 2")
  string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," bytes "${content}")

  file(APPEND "${OUTPUT_C}"
    "const unsigned char ${symbol}[] = {${bytes}0x00};\n"
    "const size_t ${symbol}_len = ${byte_length}u;\n\n")
  file(APPEND "${OUTPUT_H}"
    "extern const unsigned char ${symbol}[];\n"
    "extern const size_t ${symbol}_len;\n")
endfunction()

file(WRITE "${OUTPUT_C}"
  "/* Generated by cmake/EmbedAssets.cmake. Do not edit. */\n"
  "#include <stddef.h>\n\n")
file(WRITE "${OUTPUT_H}"
  "/* Generated by cmake/EmbedAssets.cmake. Do not edit. */\n"
  "#ifndef SYSEBA_ASSETS_H\n#define SYSEBA_ASSETS_H\n\n"
  "#include <stddef.h>\n\n")

syseba_append_asset("${HTML_FILE}" syseba_asset_html)
syseba_append_asset("${JS_FILE}" syseba_asset_js)
syseba_append_asset("${LOGO_FILE}" syseba_asset_logo)

file(APPEND "${OUTPUT_H}" "\n#endif\n")
